name: Release

on:
  push:
    tags:
      - "v**"

jobs:
  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm i

      - name: Run gulp 
        run: |
          set -xe
          npm run release

      - name: Build documents
        run: |
          set -xe
          npm run doc:base
          npm run doc:ja

      - name: Deploy document to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./built/docs
